source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'MuxLive' do
  use_frameworks!

  # Pods for MuxLive
  pod 'HaishinKit', '~> 1.7.1'
  pod 'Hue', '~> 5.0.0'
  pod 'Loaf'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
    project.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
