import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import FeedContainer from './components/FeedContainer';
import Link from 'next/link';
import SubscribeButton from './components/SubscribeButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full px-4 mx-auto grid grid-rows-[auto_1fr_auto] gap-4 md:gap-6 pb-10">
          <header>
            <div className="mx-auto h-14 flex items-center gap-4">
              <Link className="flex gap-2 font-semibold items-center" href="/">
                <YoutubeIcon className="w-8 h-8 text-red-500" />
                MyTube
              </Link>
              <div className="flex-1 ml-auto">
                <form className="max-w-sm mx-auto">
                  <input
                    className="rounded-full py-2 px-4"
                    placeholder="Search"
                    type="search"
                  />
                </form>
              </div>
              <button className="h-8">
                <FeedContainer></FeedContainer>
              </button>
              <SubscribeButton></SubscribeButton>
            </div>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}

function YoutubeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  );
}
